import sql from "@/lib/db";

export async function GET(request: Request) {
  try {
      const { searchParams } = new URL(request.url);

          const startDate =
                searchParams.get("startDate");

                    const endDate =
                          searchParams.get("endDate");

                              if (!startDate || !endDate) {
                                    return Response.json(
                                            {
                                                      success: false,
                                                                message:
                                                                            "Tanggal awal dan tanggal akhir wajib diisi",
                                                                                    },
                                                                                            { status: 400 }
                                                                                                  );
                                                                                                      }

                                                                                                          const sales = await sql`
                                                                                                                SELECT
                                                                                                                        s.id,
                                                                                                                                s.sale_date,
                                                                                                                                        s.invoice_number,
                                                                                                                                                COALESCE(c.name, 'Umum') AS customer_name,
                                                                                                                                                        s.total_amount,
                                                                                                                                                                s.payment_method,
                                                                                                                                                                        s.status
                                                                                                                                                                              FROM sales s
                                                                                                                                                                                    LEFT JOIN customers c
                                                                                                                                                                                            ON c.id = s.customer_id
                                                                                                                                                                                                  WHERE s.sale_date >= ${startDate}::date
                                                                                                                                                                                                          AND s.sale_date < (${endDate}::date + INTERVAL '1 day')
                                                                                                                                                                                                                ORDER BY s.sale_date DESC
                                                                                                                                                                                                                    `;

                                                                                                                                                                                                                        const purchases = await sql`
                                                                                                                                                                                                                              SELECT
                                                                                                                                                                                                                                      p.id,
                                                                                                                                                                                                                                              p.purchase_date,
                                                                                                                                                                                                                                                      p.invoice_number,
                                                                                                                                                                                                                                                              COALESCE(s.name, '-') AS supplier_name,
                                                                                                                                                                                                                                                                      p.total_amount,
                                                                                                                                                                                                                                                                              p.status
                                                                                                                                                                                                                                                                                    FROM purchases p
                                                                                                                                                                                                                                                                                          LEFT JOIN suppliers s
                                                                                                                                                                                                                                                                                                  ON s.id = p.supplier_id
                                                                                                                                                                                                                                                                                                        WHERE p.purchase_date >= ${startDate}::date
                                                                                                                                                                                                                                                                                                                AND p.purchase_date < (${endDate}::date + INTERVAL '1 day')
                                                                                                                                                                                                                                                                                                                      ORDER BY p.purchase_date DESC
                                                                                                                                                                                                                                                                                                                          `;

                                                                                                                                                                                                                                                                                                                              const totalSales = sales.reduce(
                                                                                                                                                                                                                                                                                                                                    (total, sale) =>
                                                                                                                                                                                                                                                                                                                                            total + Number(sale.total_amount || 0),
                                                                                                                                                                                                                                                                                                                                                  0
                                                                                                                                                                                                                                                                                                                                                      );

                                                                                                                                                                                                                                                                                                                                                          const totalPurchase = purchases.reduce(
                                                                                                                                                                                                                                                                                                                                                                (total, purchase) =>
                                                                                                                                                                                                                                                                                                                                                                        total + Number(purchase.total_amount || 0),
                                                                                                                                                                                                                                                                                                                                                                              0
                                                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                                                      return Response.json({
                                                                                                                                                                                                                                                                                                                                                                                            success: true,
                                                                                                                                                                                                                                                                                                                                                                                                  data: {
                                                                                                                                                                                                                                                                                                                                                                                                          sales: sales.map((sale) => ({
                                                                                                                                                                                                                                                                                                                                                                                                                    id: sale.id,
                                                                                                                                                                                                                                                                                                                                                                                                                              date: sale.sale_date,
                                                                                                                                                                                                                                                                                                                                                                                                                                        invoice: sale.invoice_number,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  customer: sale.customer_name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            total: Number(sale.total_amount || 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      payment: sale.payment_method,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                status: sale.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                purchases: purchases.map((purchase) => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          id: purchase.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    date: purchase.purchase_date,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              invoice: purchase.invoice_number,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        supplier: purchase.supplier_name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  total: Number(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              purchase.total_amount || 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  status: purchase.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  summary: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            totalSales,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      totalPurchase,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                totalTransaction: sales.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          estimatedProfit:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      totalSales - totalPurchase,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error(error);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return Response.json(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        message:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Gagal mengambil data laporan",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { status: 500 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }